import { motion } from 'framer-motion';
import { create } from 'zustand';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

type NodeKind = 'indicator'|'price'|'candlestick'|'logic'|'comparison'|'trade'|'risk'|'time'|'math'|'utility'|'variable';
type PortType = 'series'|'number'|'boolean'|'action'|'risk'|'time'|'any';
type BuilderNode = { id:string; type:string; kind:NodeKind; title:string; description:string; icon:string; color:string; x:number; y:number; inputs:PortType[]; outputs:PortType[]; settings:Record<string,string|number|boolean>; collapsed?:boolean; disabled?:boolean; comments?:string; favorite?:boolean };
type BuilderEdge = { id:string; source:string; target:string; sourceType:PortType; targetType:PortType; valid:boolean; error?:string };
type ValidationItem = { level:'error'|'warning'; nodeId?:string; edgeId?:string; message:string };
type StrategyJson = { version:number; name:string; nodes:BuilderNode[]; edges:BuilderEdge[]; metadata:Record<string, unknown> };

type Store = { strategy:StrategyJson; selected:string[]; clipboard:BuilderNode[]; history:StrategyJson[]; future:StrategyJson[]; savedAt:string; version:number; setStrategy:(s:StrategyJson)=>void; addNode:(n:BuilderNode)=>void; updateNode:(id:string, patch:Partial<BuilderNode>)=>void; deleteSelected:()=>void; select:(ids:string[])=>void; addEdge:(e:BuilderEdge)=>void; undo:()=>void; redo:()=>void; copy:()=>void; paste:()=>void; save:()=>void; rename:(name:string)=>void };
const uid = (p:string) => `${p}_${Math.random().toString(36).slice(2, 9)}`;
const clone = (s:StrategyJson):StrategyJson => JSON.parse(JSON.stringify(s));
const initialStrategy: StrategyJson = { version: 1, name: 'Untitled Visual Strategy', nodes: [], edges: [], metadata: { autosave: true, engine: 'visual-strategy-builder' } };
const persisted = () => { try { return JSON.parse(localStorage.getItem('bt.strategy.builder') || '') as StrategyJson; } catch { return initialStrategy; } };

const useBuilder = create<Store>((set, get) => ({
  strategy: persisted(), selected: [], clipboard: [], history: [], future: [], savedAt: 'Not saved', version: 1,
  setStrategy: (strategy) => set({ strategy }),
  addNode: (node) => set((s) => ({ history:[clone(s.strategy), ...s.history].slice(0,50), future:[], strategy:{...s.strategy, nodes:[...s.strategy.nodes, node]}, selected:[node.id] })),
  updateNode: (id, patch) => set((s) => ({ strategy:{...s.strategy, nodes:s.strategy.nodes.map((n) => n.id === id ? {...n, ...patch, settings:{...n.settings, ...(patch.settings ?? {})}} : n)} })),
  deleteSelected: () => set((s) => ({ history:[clone(s.strategy), ...s.history].slice(0,50), future:[], strategy:{...s.strategy, nodes:s.strategy.nodes.filter((n) => !s.selected.includes(n.id)), edges:s.strategy.edges.filter((e) => !s.selected.includes(e.source) && !s.selected.includes(e.target))}, selected:[] })),
  select: (selected) => set({ selected }),
  addEdge: (edge) => set((s) => ({ history:[clone(s.strategy), ...s.history].slice(0,50), future:[], strategy:{...s.strategy, edges:[...s.strategy.edges, edge]} })),
  undo: () => set((s) => s.history[0] ? { future:[clone(s.strategy), ...s.future], strategy:s.history[0], history:s.history.slice(1) } : s),
  redo: () => set((s) => s.future[0] ? { history:[clone(s.strategy), ...s.history], strategy:s.future[0], future:s.future.slice(1) } : s),
  copy: () => set((s) => ({ clipboard:s.strategy.nodes.filter((n) => s.selected.includes(n.id)).map(clone as never) })),
  paste: () => { const s=get(); s.clipboard.forEach((n, i) => get().addNode({ ...n, id:uid(n.type), x:n.x+42+(i*12), y:n.y+42+(i*12), title:`${n.title} Copy` })); },
  save: () => { const strategy=get().strategy; localStorage.setItem('bt.strategy.builder', JSON.stringify(strategy)); set({ savedAt:new Date().toLocaleTimeString(), version:get().version+1 }); },
  rename: (name) => set((s) => ({ strategy:{...s.strategy, name} })),
}));

const library: Omit<BuilderNode,'id'|'x'|'y'>[] = [
  ...['EMA','SMA','RSI','MACD','ATR','ADX','Bollinger Bands','VWAP','Stochastic','Moving Average'].map((title) => ({ type:title.toLowerCase().replaceAll(' ','_'), kind:'indicator' as const, title, description:`${title} indicator with configurable period, source, offset, and plot color.`, icon:'ƒ', color:'#22d3ee', inputs:['series'] as PortType[], outputs:['series','number'] as PortType[], settings:{ period:title==='EMA'?20:14, source:'Close', offset:0, color:'#22d3ee' } })),
  ...['Open','High','Low','Close','Volume','Bid','Ask','Spread'].map((title) => ({ type:title.toLowerCase(), kind:'price' as const, title, description:`Market ${title.toLowerCase()} data source.`, icon:'⌁', color:'#a78bfa', inputs:[] as PortType[], outputs:['series','number'] as PortType[], settings:{ timeframe:'Current' } })),
  ...['Bullish Engulfing','Bearish Engulfing','Hammer','Shooting Star','Doji','Morning Star','Evening Star'].map((title) => ({ type:title.toLowerCase().replaceAll(' ','_'), kind:'candlestick' as const, title, description:`Candlestick pattern detector for ${title}.`, icon:'▥', color:'#f59e0b', inputs:['series'] as PortType[], outputs:['boolean'] as PortType[], settings:{ lookback:3, strict:true } })),
  ...['IF','ELSE','AND','OR','NOT','Switch'].map((title) => ({ type:title.toLowerCase(), kind:'logic' as const, title, description:`Logical ${title} operator.`, icon:'◇', color:'#34d399', inputs:['boolean','boolean'] as PortType[], outputs:['boolean'] as PortType[], settings:{ enabled:true } })),
  ...['>','<','>=','<=','==','!=','Cross Above','Cross Below','Between'].map((title) => ({ type:`cmp_${title.replace(/\W+/g,'_')}`, kind:'comparison' as const, title, description:`Comparison rule: ${title}.`, icon:'⇄', color:'#60a5fa', inputs:['any','any'] as PortType[], outputs:['boolean'] as PortType[], settings:{ threshold:0 } })),
  ...['BUY','SELL','CLOSE BUY','CLOSE SELL','CLOSE ALL'].map((title) => ({ type:title.toLowerCase().replaceAll(' ','_'), kind:'trade' as const, title, description:`Trade action: ${title}.`, icon:'↯', color:'#fb7185', inputs:['boolean','risk'] as PortType[], outputs:['action'] as PortType[], settings:{ orderType:'Market', slippage:1 } })),
  ...['Stop Loss','Take Profit','Trailing Stop','Break Even','Risk %','Lot Size','Max Daily Loss','Max Open Trades'].map((title) => ({ type:title.toLowerCase().replaceAll(' ','_'), kind:'risk' as const, title, description:`Risk control: ${title}.`, icon:'◉', color:'#f97316', inputs:['number'] as PortType[], outputs:['risk'] as PortType[], settings:{ value:title.includes('%')?1:20, unit:title.includes('Loss')?'currency':'pips' } })),
  ...['London Session','New York Session','Asian Session','Custom Session','Weekday','Date Range'].map((title) => ({ type:title.toLowerCase().replaceAll(' ','_'), kind:'time' as const, title, description:`Time filter: ${title}.`, icon:'◷', color:'#14b8a6', inputs:[] as PortType[], outputs:['time','boolean'] as PortType[], settings:{ timezone:'Exchange', start:'08:00', end:'17:00' } })),
];
const categories = ['Favorites','Indicators','Price','Candlestick','Risk','Trade Actions','Sessions','Time Filters','Variables','Math','Logic','Comparison','Utilities'];
const typeOk = (a:PortType,b:PortType) => a === b || a === 'any' || b === 'any';

function SimpleStrategyWizard({ strategy }: { strategy: StrategyJson }) {
  const [language, setLanguage] = useState<'hinglish' | 'hindi' | 'english'>('hinglish');
  const [idea, setIdea] = useState('Jab EMA 20, EMA 50 ke upar cross kare aur RSI 60 se upar ho to BUY. Stop loss 30 pips, take profit 60 pips.');
  const [confirmed, setConfirmed] = useState(false);
  const [apiKey, setApiKey] = useState('');
  const [mt5Path, setMt5Path] = useState('');
  const steps = useMemo(() => idea.split(/[.\n]/).map((step) => step.trim()).filter(Boolean), [idea]);
  const template = useMemo(() => `// BackTest AI MT5 Expert Advisor Template\n// Strategy: ${strategy.name}\n// Language: ${language}\n// Confirmed steps:\n${steps.map((step, index) => `// ${index + 1}. ${step}`).join('\n')}\n\n#property strict\n#include <Trade/Trade.mqh>\nCTrade trade;\n\ninput double Lots = 0.10;\ninput int StopLossPips = 30;\ninput int TakeProfitPips = 60;\n\nint OnInit(){\n  return(INIT_SUCCEEDED);\n}\n\nvoid OnTick(){\n  // TODO: Replace this template logic with generated indicator rules after confirmation.\n}\n`, [language, steps, strategy.name]);
  const saveTemplate = () => {
    localStorage.setItem('bt.strategy.mt5.template', JSON.stringify({ strategyName: strategy.name, language, idea, steps, template, mt5Path, openAiKeyConfigured: Boolean(apiKey), savedAt: new Date().toISOString() }));
    setConfirmed(true);
  };
  return <section className="simple-builder-card"><div><span className="eyebrow">Simple mode</span><h2>Write strategy in Hindi, English, or Hinglish</h2><p>Non-technical users can describe rules in plain language, review the converted steps, confirm, and save an MT5-ready template draft for later backtesting workflow.</p></div><div className="simple-builder-grid"><label>Language<select value={language} onChange={(e)=>setLanguage(e.target.value as typeof language)}><option value="hinglish">Hinglish</option><option value="hindi">Hindi</option><option value="english">English</option></select></label><label>OpenAI API key<input value={apiKey} onChange={(e)=>setApiKey(e.target.value)} placeholder="sk-... optional for AI conversion" type="password" /></label><label>MetaTrader 5 terminal path<input value={mt5Path} onChange={(e)=>setMt5Path(e.target.value)} placeholder="C:\\Program Files\\MetaTrader 5\\terminal64.exe" /></label></div><textarea value={idea} onChange={(e)=>{setIdea(e.target.value);setConfirmed(false);}} placeholder="Example: EMA 20 cross above EMA 50 ho to BUY, RSI 60 ke upar confirm kare, SL 30 pips, TP 60 pips." /><div className="simple-steps"><h3>Converted confirmation steps</h3>{steps.map((step,index)=><p key={`${step}-${index}`}><b>{index+1}</b>{step}</p>)}{steps.length===0&&<p>No steps yet. Strategy likhiye.</p>}</div><div className="simple-actions"><button onClick={saveTemplate}>Confirm & save MT5 template</button><span>{confirmed ? 'Template saved locally. Backtesting screen can select this saved template next.' : 'Confirm karne ke baad template local storage me save hoga.'}</span></div><details><summary>MT5 template preview</summary><pre>{template}</pre></details></section>;
}

function validate(nodes:BuilderNode[], edges:BuilderEdge[]):ValidationItem[] { const out:ValidationItem[]=[]; const ids=new Set(nodes.map(n=>n.id)); edges.forEach(e=>{ if(!ids.has(e.source)||!ids.has(e.target)) out.push({level:'error', edgeId:e.id, message:'Invalid connection references a missing node.'}); if(!e.valid) out.push({level:'error', edgeId:e.id, message:e.error || 'Invalid connection type.'}); }); nodes.forEach(n=>{ if(n.inputs.length && !edges.some(e=>e.target===n.id)) out.push({level:'warning', nodeId:n.id, message:`${n.title} has missing inputs or is disconnected.`}); if(n.outputs.length && !edges.some(e=>e.source===n.id) && n.kind !== 'trade') out.push({level:'warning', nodeId:n.id, message:`${n.title} output is not connected.`}); if(n.disabled) out.push({level:'warning', nodeId:n.id, message:`${n.title} is disabled.`}); }); return out; }

export function StrategyBuilder() {
  const { strategy, selected, addNode, updateNode, deleteSelected, select, addEdge, undo, redo, copy, paste, save, rename, savedAt, version } = useBuilder();
  const [query,setQuery]=useState(''); const [category,setCategory]=useState('Indicators'); const [scale,setScale]=useState(1); const [pan,setPan]=useState({x:0,y:0}); const [connecting,setConnecting]=useState<string|null>(null); const canvas=useRef<HTMLDivElement>(null);
  const selectedNode = strategy.nodes.find(n=>n.id===selected[0]); const issues=useMemo(()=>validate(strategy.nodes,strategy.edges),[strategy]);
  const filtered = library.filter(n => (category==='Favorites'?n.favorite: category==='Trade Actions'?n.kind==='trade': category==='Sessions'||category==='Time Filters'?n.kind==='time': category.toLowerCase().startsWith(n.kind)) && n.title.toLowerCase().includes(query.toLowerCase()));
  useEffect(()=>{ const t=setInterval(save,10000); return()=>clearInterval(t); },[save]);
  useEffect(()=>{ const onKey=(e:KeyboardEvent)=>{ if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();save();} if((e.ctrlKey||e.metaKey)&&e.key==='z') undo(); if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y') redo(); if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c') copy(); if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v') paste(); if(e.key==='Delete') deleteSelected(); if(e.key===' ') setScale(1); }; window.addEventListener('keydown',onKey); return()=>window.removeEventListener('keydown',onKey); },[save,undo,redo,copy,paste,deleteSelected]);
  const dropNode = (template:Omit<BuilderNode,'id'|'x'|'y'>, x=120, y=120) => addNode({...template, id:uid(template.type), x:Math.round((x-pan.x)/20)*20, y:Math.round((y-pan.y)/20)*20});
  const connect = useCallback((target:string) => { if(!connecting || connecting===target) return setConnecting(null); const s=strategy.nodes.find(n=>n.id===connecting)!; const t=strategy.nodes.find(n=>n.id===target)!; const st=s.outputs[0]||'any'; const tt=t.inputs[0]||'any'; const valid=typeOk(st,tt) && !strategy.edges.some(e=>e.source===target&&e.target===connecting); addEdge({id:uid('edge'), source:connecting, target, sourceType:st, targetType:tt, valid, error:valid?undefined:`${st} output cannot connect to ${tt} input`}); setConnecting(null); },[connecting,strategy,addEdge]);
  return <div className="builder-workspace"><SimpleStrategyWizard strategy={strategy} /><div className="builder-shell">
    <aside className="builder-left"><div className="builder-title"><b>Node Library</b><span>React Flow-ready JSON graph</span></div><input className="input" placeholder="Search nodes…" value={query} onChange={e=>setQuery(e.target.value)} /><div className="category-list">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="node-palette">{filtered.map(n=><motion.button whileHover={{x:4}} key={n.type} draggable onDragEnd={(_,info)=>dropNode(n, info.point.x, info.point.y)} onClick={()=>dropNode(n, 180+strategy.nodes.length*24, 160+strategy.nodes.length*18)}><span style={{background:n.color}}>{n.icon}</span><b>{n.title}</b><small>{n.description}</small></motion.button>)}</div></aside>
    <main className="builder-center"><div className="builder-toolbar"><input value={strategy.name} onChange={e=>rename(e.target.value)} /><button onClick={undo}>Undo</button><button onClick={redo}>Redo</button><button onClick={copy}>Copy</button><button onClick={paste}>Paste</button><button onClick={deleteSelected}>Delete</button><button onClick={()=>setScale(s=>Math.max(.4,s-.1))}>−</button><button onClick={()=>setScale(s=>Math.min(2,s+.1))}>+</button><button onClick={save}>Manual Save</button><span>v{version} · {savedAt} · autosaves every 10s</span></div><div className="flow-canvas" ref={canvas} onWheel={e=>setScale(s=>Math.min(2,Math.max(.4,s-(e.deltaY/1200))))} onDoubleClick={()=>select([])}><svg className="edge-layer">{strategy.edges.map(e=>{const a=strategy.nodes.find(n=>n.id===e.source), b=strategy.nodes.find(n=>n.id===e.target); if(!a||!b) return null; return <path key={e.id} className={e.valid?'edge':'edge invalid'} d={`M ${a.x+220} ${a.y+48} C ${a.x+320} ${a.y+48}, ${b.x-100} ${b.y+48}, ${b.x} ${b.y+48}`} />})}</svg><div className="flow-board" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${scale})`}}>{strategy.nodes.map(n=><motion.article drag dragMomentum={false} onDragEnd={(_,i)=>updateNode(n.id,{x:Math.round((n.x+i.offset.x)/20)*20,y:Math.round((n.y+i.offset.y)/20)*20})} className={`strategy-node ${selected.includes(n.id)?'selected':''} ${n.disabled?'disabled':''}`} style={{left:n.x,top:n.y,borderColor:n.color}} key={n.id} onClick={(e)=>{ e.stopPropagation(); e.shiftKey?select([...selected,n.id]): connecting?connect(n.id):select([n.id]); }}><header><span style={{background:n.color}}>{n.icon}</span><b>{n.title}</b><button onClick={(e)=>{e.stopPropagation();updateNode(n.id,{collapsed:!n.collapsed})}}>{n.collapsed?'▸':'▾'}</button></header>{!n.collapsed&&<><p>{n.description}</p><div className="ports"><button onClick={(e)=>{e.stopPropagation();setConnecting(n.id)}}>out {n.outputs.join(', ')||'—'}</button><small>in {n.inputs.join(', ')||'—'}</small></div><footer><button onClick={(e)=>{e.stopPropagation();addNode({...n,id:uid(n.type),x:n.x+40,y:n.y+40,title:`${n.title} Copy`})}}>Duplicate</button><button onClick={(e)=>{e.stopPropagation();updateNode(n.id,{disabled:!n.disabled})}}>{n.disabled?'Enable':'Disable'}</button></footer></>}</motion.article>)}</div><div className="minimap">{strategy.nodes.map(n=><i key={n.id} style={{left:n.x/12, top:n.y/12, background:n.color}} />)}</div><div className="canvas-hint">Zoom {Math.round(scale*100)}% · snap 20px · {selected.length} selected</div></div></main>
    <aside className="builder-right"><h3>Properties</h3>{selectedNode ? <div className="properties"><b>{selectedNode.title}</b><p>{selectedNode.description}</p><label>Title<input className="input" value={selectedNode.title} onChange={e=>updateNode(selectedNode.id,{title:e.target.value})}/></label><label>Description<textarea value={selectedNode.description} onChange={e=>updateNode(selectedNode.id,{description:e.target.value})}/></label>{Object.entries(selectedNode.settings).map(([k,v])=><label key={k}>{k}<input className="input" value={String(v)} onChange={e=>updateNode(selectedNode.id,{settings:{[k]:Number.isNaN(Number(e.target.value))?e.target.value:Number(e.target.value)}})}/></label>)}<label>Comments<textarea value={selectedNode.comments || ''} onChange={e=>updateNode(selectedNode.id,{comments:e.target.value})}/></label></div> : <p>Select a node to edit settings, validation, documentation, comments, collapse state, and disable state.</p>}<h3>Validation</h3><div className="validation-list">{issues.length===0?<p className="ok">No errors. Strategy JSON is valid.</p>:issues.map((i,idx)=><p key={idx} className={i.level}>{i.level.toUpperCase()}: {i.message}</p>)}</div><h3>Strategy JSON</h3><pre>{JSON.stringify(strategy,null,2)}</pre></aside>
  </div></div>;
}
