import type { FastifyPluginAsync } from 'fastify';
import { hashPassword, verifyPassword, sanitizeEmail, randomToken, hashToken, signJwt } from '../auth/crypto.js';
import { changePasswordSchema, forgotSchema, loginSchema, registerSchema, resetSchema, tokenSchema } from '../auth/schemas.js';
import { config } from '../config.js';
const days = (n:number) => new Date(Date.now()+n*86400_000);
const publicUser = (u:any) => ({ id:u.id, email:u.email, name:u.name, avatarUrl:u.avatarUrl, emailVerifiedAt:u.emailVerifiedAt, roles:u.roles?.map((r:any)=>r.name) ?? [] });
async function issue(app:any, user:any, req:any, remember=false) { const roles = user.roles.map((r:any)=>r.name); const session = await app.prisma.session.create({ data:{ userId:user.id, ipAddress:req.ip, userAgent:req.headers['user-agent'], expiresAt:days(remember?config.REFRESH_TTL_DAYS:1) }}); const raw = randomToken(); await app.prisma.refreshToken.create({ data:{ userId:user.id, sessionId:session.id, tokenHash:hashToken(raw), family:session.id, expiresAt:session.expiresAt }}); return { accessToken:signJwt({ id:user.id, email:user.email, roles, sessionId:session.id }), refreshToken:raw, user:publicUser(user) }; }
export const authRoutes: FastifyPluginAsync = async (app) => {
 app.post('/auth/register', { schema:{ tags:['Auth'] } }, async (req, reply) => { const input = registerSchema.parse(req.body); const email=sanitizeEmail(input.email); const role = await app.prisma.role.upsert({ where:{ name:'FREE_USER' }, update:{}, create:{ name:'FREE_USER' }}); const user = await app.prisma.user.create({ data:{ email, name:input.name, passwordHash:await hashPassword(input.password), roles:{ connect:{ id:role.id }}} , include:{ roles:true }}); const token=randomToken(); await app.prisma.emailVerification.create({ data:{ userId:user.id, tokenHash:hashToken(token), expiresAt:days(1) }}); req.log.info({ email, verificationToken:token }, 'mock verification email'); return reply.code(201).send({ user:publicUser(user), verificationToken: token }); });
 app.post('/auth/login', { config:{ rateLimit:{ max:5, timeWindow:'1 minute' } }, schema:{ tags:['Auth'] } }, async (req, reply) => { const input=loginSchema.parse(req.body); const email=sanitizeEmail(input.email); const user=await app.prisma.user.findUnique({ where:{ email }, include:{ roles:true }}); const ok = user?.isActive && await verifyPassword(input.password, user.passwordHash); await app.prisma.loginHistory.create({ data:{ userId:user?.id, email, ipAddress:req.ip, userAgent:req.headers['user-agent'], success:!!ok, reason:ok?'OK':'INVALID_CREDENTIALS' }}); if (!ok) return reply.code(401).send({ message:'Invalid credentials' }); return issue(app,user,req,input.rememberMe); });
 app.post('/auth/logout', { preHandler:app.authenticate, schema:{ tags:['Auth'] } }, async (req) => { await app.prisma.session.updateMany({ where:{ id:req.user!.sessionId }, data:{ status:'REVOKED', revokedAt:new Date() }}); await app.prisma.refreshToken.updateMany({ where:{ sessionId:req.user!.sessionId, revokedAt:null }, data:{ revokedAt:new Date() }}); return { ok:true }; });
 app.post('/auth/refresh', { schema:{ tags:['Auth'] } }, async (req, reply) => { const { token }=tokenSchema.parse(req.body); const existing=await app.prisma.refreshToken.findUnique({ where:{ tokenHash:hashToken(token) }, include:{ user:{ include:{ roles:true }}, session:true }}); if (!existing || existing.revokedAt || existing.expiresAt < new Date() || existing.session.status !== 'ACTIVE') return reply.code(401).send({ message:'Invalid refresh token' }); const raw=randomToken(); const next=await app.prisma.refreshToken.create({ data:{ userId:existing.userId, sessionId:existing.sessionId, family:existing.family, tokenHash:hashToken(raw), expiresAt:existing.expiresAt }}); await app.prisma.refreshToken.update({ where:{ id:existing.id }, data:{ revokedAt:new Date(), replacedById:next.id }}); const roles = existing.user.roles.map((r:any)=>r.name); return { accessToken:signJwt({ id:existing.user.id, email:existing.user.email, roles, sessionId:existing.sessionId }), refreshToken:raw, user:publicUser(existing.user) }; });
 app.post('/auth/forgot-password', { schema:{ tags:['Auth'] } }, async (req) => { const { email }=forgotSchema.parse(req.body); const user=await app.prisma.user.findUnique({ where:{ email:sanitizeEmail(email) }}); if (user) { const token=randomToken(); await app.prisma.passwordReset.create({ data:{ userId:user.id, tokenHash:hashToken(token), expiresAt:days(1) }}); req.log.info({ email, resetToken:token }, 'mock password reset email'); } return { ok:true }; });
 app.post('/auth/reset-password', { schema:{ tags:['Auth'] } }, async (req, reply) => { const input=resetSchema.parse(req.body); const row=await app.prisma.passwordReset.findUnique({ where:{ tokenHash:hashToken(input.token) }}); if (!row || row.usedAt || row.expiresAt < new Date()) return reply.code(400).send({ message:'Invalid reset token' }); await app.prisma.user.update({ where:{ id:row.userId }, data:{ passwordHash:await hashPassword(input.password) }}); await app.prisma.passwordReset.update({ where:{ id:row.id }, data:{ usedAt:new Date() }}); return { ok:true }; });
 app.post('/auth/verify-email', { schema:{ tags:['Auth'] } }, async (req, reply) => { const { token }=tokenSchema.parse(req.body); const row=await app.prisma.emailVerification.findUnique({ where:{ tokenHash:hashToken(token) }}); if (!row || row.verifiedAt || row.expiresAt < new Date()) return reply.code(400).send({ message:'Invalid verification token' }); await app.prisma.$transaction([app.prisma.emailVerification.update({ where:{ id:row.id }, data:{ verifiedAt:new Date() }}), app.prisma.user.update({ where:{ id:row.userId }, data:{ emailVerifiedAt:new Date() }})]); return { ok:true }; });
};
