import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { config } from '../config.js';
import type { StrategyRules } from './types.js';

const safeName = (name: string) => name.replace(/[^a-z0-9_-]/gi, '_').slice(0, 60) || 'Strategy';

type SignalPlan = { usesEma: boolean; emaPeriod: number; usesRsi: boolean; rsiLevel: number; fallback: boolean };

export function generateMql5Source(id: string, rules: StrategyRules): string {
  const name = safeName(rules.strategyName);
  const plan = buildSignalPlan(rules);
  return `//+------------------------------------------------------------------+\n//| ${name}.mq5 - generated by BackTest AI Strategy Builder          |\n//| Manages only positions opened with the configured MagicNumber.   |\n//+------------------------------------------------------------------+\n#property strict\n#include <Trade/Trade.mqh>\n\ninput double LotSize = 0.01;\ninput int StopLossPoints = 300;\ninput int TakeProfitPoints = 600;\ninput int MaxSpreadPoints = 50;\ninput long MagicNumber = ${magicFromId(id)};\ninput ENUM_TIMEFRAMES StrategyTimeframe = ${timeframeEnum(rules.timeframe)};\ninput int EmaPeriod = ${plan.emaPeriod};\ninput int RsiPeriod = 14;\ninput double RsiBuyLevel = ${plan.rsiLevel};\n\nCTrade trade;\ndatetime lastBarTime = 0;\nint emaHandle = INVALID_HANDLE;\nint rsiHandle = INVALID_HANDLE;\n\nint OnInit()\n{\n   trade.SetExpertMagicNumber(MagicNumber);\n${plan.usesEma ? '   emaHandle = iMA(_Symbol, StrategyTimeframe, EmaPeriod, 0, MODE_EMA, PRICE_CLOSE);\n   if(emaHandle == INVALID_HANDLE) return INIT_FAILED;\n' : ''}${plan.usesRsi ? '   rsiHandle = iRSI(_Symbol, StrategyTimeframe, RsiPeriod, PRICE_CLOSE);\n   if(rsiHandle == INVALID_HANDLE) return INIT_FAILED;\n' : ''}   return INIT_SUCCEEDED;\n}\n\nvoid OnDeinit(const int reason)\n{\n   if(emaHandle != INVALID_HANDLE) IndicatorRelease(emaHandle);\n   if(rsiHandle != INVALID_HANDLE) IndicatorRelease(rsiHandle);\n}\n\nvoid OnTick()\n{\n   if(!IsNewBar()) return;\n   if(SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) > MaxSpreadPoints) return;\n   if(HasOpenMagicPosition()) return;\n\n   // Strategy: ${escapeComment(rules.description)}\n   // Entry: ${escapeComment(rules.entryCondition ?? 'AI-generated entry rules')}\n   if(EntrySignal())\n   {\n      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);\n      double sl = NormalizeDouble(ask - StopLossPoints * _Point, _Digits);\n      double tp = NormalizeDouble(ask + TakeProfitPoints * _Point, _Digits);\n      trade.Buy(LotSize, _Symbol, ask, sl, tp, "${name}");\n   }\n}\n\nbool EntrySignal()\n{\n${entrySignalCode(plan)}\n}\n\nbool HasOpenMagicPosition()\n{\n   for(int i = PositionsTotal() - 1; i >= 0; i--)\n   {\n      ulong ticket = PositionGetTicket(i);\n      if(ticket > 0 && PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)\n         return true;\n   }\n   return false;\n}\n\nbool IsNewBar()\n{\n   datetime current = iTime(_Symbol, StrategyTimeframe, 0);\n   if(current == 0 || current == lastBarTime) return false;\n   lastBarTime = current;\n   return true;\n}\n`;
}

export function validateMql5Source(source: string) {
  const forbidden = ['ShellExecute', 'WinExec', '#import', 'FileDelete', 'FileMove', 'WebRequest'];
  const found = forbidden.find((token) => source.includes(token));
  if (found) throw new Error(`Generated MQL5 contains forbidden token: ${found}`);
}

export async function writeStrategyFolder(id: string, rules: StrategyRules, source: string) {
  validateMql5Source(source);
  const root = path.resolve(config.GENERATED_STRATEGY_DIR, id);
  if (!root.startsWith(path.resolve(config.GENERATED_STRATEGY_DIR))) throw new Error('Invalid generated strategy path');
  await mkdir(root, { recursive: true });
  const mq5Path = path.join(root, `${safeName(rules.strategyName)}.mq5`);
  await writeFile(path.join(root, 'strategy.json'), JSON.stringify(rules, null, 2));
  await writeFile(mq5Path, source);
  await writeFile(path.join(root, 'README.md'), `# ${rules.strategyName}\n\nMQ5 Expert Advisor generated from the saved template. Compile this file in MetaEditor to create EX5 if server compiler is unavailable.\n`);
  return { root, mq5Path };
}

export async function compileMql5(mq5Path: string) {
  if (!config.METAEDITOR_PATH) return { compiled: false, message: 'MQ5 file generated. Please compile it in MetaEditor to create EX5.' };
  return new Promise<{ compiled: boolean; message: string; ex5Path?: string }>((resolve) => {
    const child = spawn(config.METAEDITOR_PATH!, [`/compile:${mq5Path}`], { shell: false, timeout: 30000 });
    let output = '';
    child.stdout.on('data', (d) => output += d);
    child.stderr.on('data', (d) => output += d);
    child.on('close', (code) => resolve({ compiled: code === 0, message: output || `Compiler exited with ${code}`, ex5Path: mq5Path.replace(/\.mq5$/i, '.ex5') }));
    child.on('error', () => resolve({ compiled: false, message: 'MQ5 file generated. Please compile it in MetaEditor to create EX5.' }));
  });
}

function buildSignalPlan(rules: StrategyRules): SignalPlan {
  const text = `${rules.description} ${rules.entryCondition ?? ''}`;
  const emaPeriod = Number(text.match(/EMA\s*(\d+)/i)?.[1] ?? 210);
  const rsiLevel = Number(text.match(/RSI\s*(\d+)/i)?.[1] ?? 30);
  const usesEma = /EMA/i.test(text) || rules.indicators.includes('EMA');
  const usesRsi = /RSI/i.test(text) || rules.indicators.includes('RSI');
  return { usesEma, emaPeriod, usesRsi, rsiLevel, fallback: !usesEma && !usesRsi };
}

function entrySignalCode(plan: SignalPlan) {
  if (plan.usesEma && !plan.usesRsi) {
    return `   double emaBuffer[2];\n   ArraySetAsSeries(emaBuffer, true);\n   if(CopyBuffer(emaHandle, 0, 0, 2, emaBuffer) < 2) return false;\n   double closePrice = iClose(_Symbol, StrategyTimeframe, 1);\n   return closePrice > emaBuffer[1];`;
  }
  if (plan.usesRsi && !plan.usesEma) {
    return `   double rsiBuffer[3];\n   ArraySetAsSeries(rsiBuffer, true);\n   if(CopyBuffer(rsiHandle, 0, 0, 3, rsiBuffer) < 3) return false;\n   return rsiBuffer[2] < RsiBuyLevel && rsiBuffer[1] >= RsiBuyLevel;`;
  }
  if (plan.usesEma && plan.usesRsi) {
    return `   double emaBuffer[2];\n   double rsiBuffer[3];\n   ArraySetAsSeries(emaBuffer, true);\n   ArraySetAsSeries(rsiBuffer, true);\n   if(CopyBuffer(emaHandle, 0, 0, 2, emaBuffer) < 2) return false;\n   if(CopyBuffer(rsiHandle, 0, 0, 3, rsiBuffer) < 3) return false;\n   double closePrice = iClose(_Symbol, StrategyTimeframe, 1);\n   bool trendOk = closePrice > emaBuffer[1];\n   bool rsiCross = rsiBuffer[2] < RsiBuyLevel && rsiBuffer[1] >= RsiBuyLevel;\n   return trendOk && rsiCross;`;
  }
  return `   // Fallback executable behavior: trade first new bar only after user confirms concrete indicator rules.\n   // Keep this conservative so templates with missing rules do not overtrade in backtests.\n   return false;`;
}

const timeframeEnum = (tf: string | null) => tf ? `PERIOD_${tf.toUpperCase()}` : 'PERIOD_CURRENT';
const magicFromId = (id: string) => Math.abs([...id].reduce((a, c) => ((a * 31) + c.charCodeAt(0)) | 0, 7));
const escapeComment = (value: string) => value.replace(/[\r\n]+/g, ' ').replace(/\*\//g, '* /');
