import { useCallback, type DragEvent } from 'react';
import { Background, Controls, MiniMap, ReactFlow, ReactFlowProvider, addEdge, applyEdgeChanges, applyNodeChanges, useReactFlow, type Connection, type EdgeChange, type Node, type NodeChange, type NodeTypes } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useMutation } from '@tanstack/react-query';
import { STRATEGY_GRAPH_VERSION } from '@backtest-ai/shared';
import { BlockNode } from './BlockNode';import { Palette } from './Palette';import { loadStrategy, saveStrategy } from '../../lib/api';import { useBuilderStore } from '../../store/builderStore';
const nodeTypes:NodeTypes={block:BlockNode};
function CanvasInner(){const rf=useReactFlow();const s=useBuilderStore();const load=useMutation({mutationFn:(id:string)=>loadStrategy(id),onSuccess:(data)=>s.setStrategy(data.id,data.name,data.graph.nodes,data.graph.edges)});const save=useMutation({mutationFn:()=>saveStrategy({id:s.strategyId,name:s.strategyName,graph:{nodes:s.nodes,edges:s.edges,version:STRATEGY_GRAPH_VERSION}}),onSuccess:(data)=>s.setStrategy(data.id,data.name,data.graph.nodes,data.graph.edges)});const onDrop=useCallback((event:DragEvent)=>{event.preventDefault();const raw=event.dataTransfer.getData('application/backtest-block');if(!raw)return;const block=JSON.parse(raw);const position=rf.screenToFlowPosition({x:event.clientX,y:event.clientY});const node:Node={id:crypto.randomUUID(),type:'block',position,data:block};s.commit([...s.nodes,node],s.edges);},[rf,s]);return <div className="flex h-full"><Palette/><main className="flex min-w-0 flex-1 flex-col"><div className="flex items-center gap-2 border-b border-slate-800 bg-slate-950 px-4 py-3"><input value={s.strategyName} onChange={e=>useBuilderStore.setState({strategyName:e.target.value})} className="rounded-md border border-slate-700 bg-slate-900 px-3 py-2 font-semibold"/><button onClick={()=>save.mutate()} className="rounded-md bg-cyan-500 px-4 py-2 font-semibold text-slate-950">Save</button><button onClick={()=>{const id=globalThis.prompt('Strategy ID to load'); if(id) load.mutate(id)}}>Load</button><button onClick={s.undo}>Undo</button><button onClick={s.redo}>Redo</button><button onClick={()=>s.copy(s.nodes.filter(n=>n.selected))}>Copy</button><button onClick={s.paste}>Paste</button><button onClick={()=>s.commit(s.nodes.flatMap(n=>n.selected?[n,{...n,id:crypto.randomUUID(),position:{x:n.position.x+40,y:n.position.y+40},selected:false}]:[n]),s.edges)}>Duplicate</button><span className="ml-auto text-sm text-slate-400">{save.isSuccess?'Saved':save.isPending?'Saving':''}</span></div><div className="flex-1" onDrop={onDrop} onDragOver={e=>e.preventDefault()}><ReactFlow nodes={s.nodes} edges={s.edges} nodeTypes={nodeTypes} onNodesChange={(changes:NodeChange[])=>s.setGraph(applyNodeChanges(changes,s.nodes),s.edges)} onEdgesChange={(changes:EdgeChange[])=>s.setGraph(s.nodes,applyEdgeChanges(changes,s.edges))} onConnect={(c:Connection)=>s.commit(s.nodes,addEdge(c,s.edges))} fitView snapToGrid snapGrid={[16,16]} deleteKeyCode={['Backspace','Delete']} multiSelectionKeyCode="Shift"><Background gap={16}/><MiniMap/><Controls/></ReactFlow></div></main></div>}
export function StrategyCanvas(){return <ReactFlowProvider><CanvasInner/></ReactFlowProvider>}
